import React, { createContext, useContext, useEffect, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  ro: {
    welcome: 'Bun venit la CarXSell',
    heroDescription: 'Platforma ta de încredere pentru vânzări și închirieri auto',
    exploreSales: 'Explorează Vânzări',
    exploreRentals: 'Explorează Închirieri',
    whyChooseUs: 'De ce să alegi CarXSell?',
    widestSelection: 'Cea mai mare selecție',
    widestSelectionDesc: 'Mii de mașini disponibile pentru vânzare și închiriere',
    directChat: 'Chat Direct',
    directChatDesc: 'Comunică instant cu vânzătorii și proprietarii',
    multiLanguage: 'Multilingv',
    multiLanguageDesc: 'Disponibil în 7 limbi pentru confortul tău',
    featuredCars: 'Mașini Recomandate',
    viewAll: 'Vezi toate',
    readyToStart: 'Pregătit să începi?',
    joinThousands: 'Alătură-te miilor de utilizatori mulțumiți',
    createAccount: 'Creează Cont',
    browseCars: 'Caută Mașini',
    searchPreferredCar: 'Caută mașina preferată',
    rentals: 'Închirieri Auto',
    addListing: 'Adaugă Anunț',
    myListings: 'Anunțurile Mele',
    profile: 'Profil',
    messages: 'Mesaje',
    logout: 'Deconectare',
    login: 'Autentificare',
    register: 'Înregistrare',
  },
  hu: {
    welcome: 'Üdvözöl az CarXSell',
    heroDescription: 'Megbízható platform autók eladására és bérlésére',
    exploreSales: 'Eladások böngészése',
    exploreRentals: 'Bérlések böngészése',
    whyChooseUs: 'Miért válaszd az CarXSell-et?',
    widestSelection: 'Legnagyobb választék',
    widestSelectionDesc: 'Ezer autó eladásra és bérlésre',
    directChat: 'Közvetlen Chat',
    directChatDesc: 'Azonnali kommunikáció eladókkal és tulajdonosokkal',
    multiLanguage: 'Többnyelvű',
    multiLanguageDesc: '7 nyelven elérhető a kényelmed érdekében',
    featuredCars: 'Kiemelt Autók',
    viewAll: 'Összes megtekintése',
    readyToStart: 'Készen állsz az indulásra?',
    joinThousands: 'Csatlakozz ezer elégedett felhasználóhoz',
    createAccount: 'Fiók létrehozása',
    browseCars: 'Autók keresése',
    searchPreferredCar: 'Keress kedvenc autót',
    rentals: 'Autóbérlés',
    addListing: 'Hirdetés hozzáadása',
    myListings: 'Hirdetéseim',
    profile: 'Profil',
    messages: 'Üzenetek',
    logout: 'Kijelentkezés',
    login: 'Bejelentkezés',
    register: 'Regisztráció',
  },
  en: {
    welcome: 'Welcome to CarXSell',
    heroDescription: 'Your trusted platform for car sales and rentals',
    exploreSales: 'Explore Sales',
    exploreRentals: 'Explore Rentals',
    whyChooseUs: 'Why Choose CarXSell?',
    widestSelection: 'Widest Selection',
    widestSelectionDesc: 'Thousands of cars available for sale and rent',
    directChat: 'Direct Chat',
    directChatDesc: 'Communicate instantly with sellers and owners',
    multiLanguage: 'Multilingual',
    multiLanguageDesc: 'Available in 7 languages for your convenience',
    featuredCars: 'Featured Cars',
    viewAll: 'View All',
    readyToStart: 'Ready to Start?',
    joinThousands: 'Join thousands of satisfied users',
    createAccount: 'Create Account',
    browseCars: 'Browse Cars',
    searchPreferredCar: 'Search Preferred Car',
    rentals: 'Car Rentals',
    addListing: 'Add Listing',
    myListings: 'My Listings',
    profile: 'Profile',
    messages: 'Messages',
    logout: 'Logout',
    login: 'Login',
    register: 'Register',
  },
  fr: {
    welcome: 'Bienvenue sur CarXSell',
    heroDescription: 'Votre plateforme de confiance pour la vente et location de voitures',
    exploreSales: 'Explorer les ventes',
    exploreRentals: 'Explorer les locations',
    whyChooseUs: 'Pourquoi choisir CarXSell?',
    widestSelection: 'Plus large sélection',
    widestSelectionDesc: 'Des milliers de voitures disponibles à la vente et à la location',
    directChat: 'Chat Direct',
    directChatDesc: 'Communiquez instantanément avec les vendeurs et propriétaires',
    multiLanguage: 'Multilingue',
    multiLanguageDesc: 'Disponible en 7 langues pour votre confort',
    featuredCars: 'Voitures en vedette',
    viewAll: 'Voir tout',
    readyToStart: 'Prêt à commencer?',
    joinThousands: 'Rejoignez des milliers d\'utilisateurs satisfaits',
    createAccount: 'Créer un compte',
    browseCars: 'Parcourir les voitures',
    searchPreferredCar: 'Rechercher voiture préférée',
    rentals: 'Location de voitures',
    addListing: 'Ajouter annonce',
    myListings: 'Mes annonces',
    profile: 'Profil',
    messages: 'Messages',
    logout: 'Déconnexion',
    login: 'Connexion',
    register: 'Inscription',
  },
  de: {
    welcome: 'Willkommen bei CarXSell',
    heroDescription: 'Ihre vertrauenswürdige Plattform für Autoverkauf und -vermietung',
    exploreSales: 'Verkäufe erkunden',
    exploreRentals: 'Vermietungen erkunden',
    whyChooseUs: 'Warum CarXSell wählen?',
    widestSelection: 'Größte Auswahl',
    widestSelectionDesc: 'Tausende Autos zum Verkauf und zur Miete verfügbar',
    directChat: 'Direkter Chat',
    directChatDesc: 'Sofortige Kommunikation mit Verkäufern und Eigentümern',
    multiLanguage: 'Mehrsprachig',
    multiLanguageDesc: 'In 7 Sprachen für Ihren Komfort verfügbar',
    featuredCars: 'Empfohlene Autos',
    viewAll: 'Alle anzeigen',
    readyToStart: 'Bereit zu starten?',
    joinThousands: 'Schließen Sie sich Tausenden zufriedenen Nutzern an',
    createAccount: 'Konto erstellen',
    browseCars: 'Autos durchsuchen',
    searchPreferredCar: 'Bevorzugtes Auto suchen',
    rentals: 'Autovermietung',
    addListing: 'Anzeige hinzufügen',
    myListings: 'Meine Anzeigen',
    profile: 'Profil',
    messages: 'Nachrichten',
    logout: 'Abmelden',
    login: 'Anmelden',
    register: 'Registrieren',
  },
  es: {
    welcome: 'Bienvenido a CarXSell',
    heroDescription: 'Tu plataforma de confianza pentru vânzări și închirieri auto',
    exploreSales: 'Explorar ventas',
    exploreRentals: 'Explorar alquileres',
    whyChooseUs: '¿Por qué elegir CarXSell?',
    widestSelection: 'Mayor selección',
    widestSelectionDesc: 'Miles de coches disponibles para venta y alquiler',
    directChat: 'Chat Directo',
    directChatDesc: 'Comunícate instantáneamente con vendedores y propietarios',
    multiLanguage: 'Multilingüe',
    multiLanguageDesc: 'Disponible en 7 idiomas para tu comodidad',
    featuredCars: 'Coches Destacados',
    viewAll: 'Ver todos',
    readyToStart: '¿Listo para comenzar?',
    joinThousands: 'Únete a miles de usuarios satisfechos',
    createAccount: 'Crear cuenta',
    browseCars: 'Buscar coches',
    searchPreferredCar: 'Buscar coche preferido',
    rentals: 'Alquiler de coches',
    addListing: 'Añadir anuncio',
    myListings: 'Mis anuncios',
    profile: 'Profil',
    messages: 'Mensajes',
    logout: 'Cerrar sesión',
    login: 'Iniciar sesión',
    register: 'Registrarse',
  },
  it: {
    welcome: 'Benvenuto su CarXSell',
    heroDescription: 'La tua piattaforma di fiducia pentru vânzări și închirieri auto',
    exploreSales: 'Esplora vendite',
    exploreRentals: 'Esplora noleggi',
    whyChooseUs: 'Perché scegliere CarXSell?',
    widestSelection: 'Selezione più ampia',
    widestSelectionDesc: 'Migliaia di auto disponibile pentru vendita e noleggio',
    directChat: 'Chat Diretta',
    directChatDesc: 'Comunica istantaneamente cu venditori e proprietari',
    multiLanguage: 'Multilingue',
    multiLanguageDesc: 'Disponibile in 7 lingue per la tua comodità',
    featuredCars: 'Auto in evidenza',
    viewAll: 'Vedi tutti',
    readyToStart: 'Pronto per iniziare?',
    joinThousands: 'Unisciti a migliaia di utenti soddisfatti',
    createAccount: 'Crea account',
    browseCars: 'Cerca auto',
    searchPreferredCar: 'Cerca auto preferita',
    rentals: 'Noleggio auto',
    addListing: 'Aggiungi annuncio',
    myListings: 'I miei annunci',
    profile: 'Profilo',
    messages: 'Messaggi',
    logout: 'Disconnetti',
    login: 'Accedi',
    register: 'Registrati',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => localStorage.getItem('selectedLanguage') || 'ro');

  useEffect(() => {
    localStorage.setItem('selectedLanguage', language);
  }, [language]);

  const t = (key) => translations[language]?.[key] || translations.ro[key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);